name: Build linux

on:
  workflow_dispatch:

jobs:

  build:
    name: Build with ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0

      - name: Install dependencies
        run: yarn install
